CREATE TABLE cmdb_ci_computer (
  id SERIAL PRIMARY KEY,
  name TEXT,
  manufacturer TEXT,
  class TEXT,
  serial_number TEXT,
  operating_system TEXT,
  os_version TEXT,
  city TEXT,
  user_id TEXT,
  is_active BOOLEAN,
  is_vip BOOLEAN,
  title TEXT,
  last_login_time TIMESTAMP,
  mobile_phone TEXT,
  employee_id INT,
  business_unit TEXT,
  is_virtual BOOLEAN,
  is_deleted BOOLEAN,
  most_recent_discovery TIMESTAMP,
  last_logged_user TEXT,
  last_logged_in_user TEXT,
  location TEXT,
  city_location TEXT,
  site_code TEXT,
  updated_by TEXT,
  updated_time TIMESTAMP DEFAULT current_timestamp
);